### ISSUE TITLE
Bounce sshd failing

### ISSUE THREAD

**Issue by tinyroy** [telusdigital/ansible-openssh#1]
ansible-playbook is failing at the following:
TASK: [package/openssh | Bounce sshd to write new pidfile.] *******************
failed: [management.uss-consumer-development.teluswebteam.com] => {"failed": true}

I commented out the restart section of openssh and the playbook continued:
roles/package/openssh/tasks/install.yml

**Comment by noqcks** [comment]
No more bouncing.
